Feat/control channel
wtfnotavailable/Discord-MusicBot pull request #40
Opened 2023-08-07 03:21 UTC by Neko-Life

## Draft
- [ ] Create dedicated query channel system
- [ ] Bring back add control buttons to now playing embed

## Please describe the changes this PR makes and why it should be merged:
Fix #39 

## Status and versioning classification:

2023-08-07 12:53 UTC, BioCla commented on djs-bot/lib/embeds.js
Move this to `djs-bot/util/`

2023-08-11 19:40 UTC, BioCla commented
Awesome work! 👍

2023-08-11 20:27 UTC, BioCla approved these changes
ong, a legend!

2023-08-11 20:27 UTC, BioCla commented
I was having so many problems with the help command ;-;

2023-08-14 07:07 UTC, BioCla commented on djs-bot/loaders/events/interactionCreate.js
> +		// !TODO: what's this for?
Was left here from v4 iirc, supposed to consider sub commands but I never got to actually implementing them ehe

2023-08-20 17:39 UTC, BioCla requested changes, later dismissed
this is creating a conflict.
Since I pushed it directly to main branch, revert?

2023-08-20 17:40 UTC, BioCla commented
For this conflict:
> djs-bot/tsconfig.json

Just take changes from main branch until actual ts is implemented

2023-08-23 10:39 UTC, Neko-Life commented
is there anything more to do

2023-08-23 10:40 UTC, BioCla commented
> is there anything more to do

Not for this PR i think.
Next steps are out of scope for this milestone

2023-08-23 10:41 UTC, merged